Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Завдання
Завдання 1: Оновлення інформації про клієнта (2 бали)
Створіть функцію для оновлення контактної інформації клієнта за його номером з наступними можливостями:

Оновлення телефону клієнта
Оновлення email (якщо поле існує в таблиці)
Опціонально, якщо вам хочеться більше практики:

Логування змін в окрему таблицю
Використайте підхід з параметризованими запитами через text() та UPDATE оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом

  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [1]:
pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\dell\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

# Завантажити .env
load_dotenv()

engine_url = f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
engine = create_engine(engine_url)

if engine is not None:
    print("Engine створено успішно!")
    display(engine)

Engine створено успішно!

Engine(mysql+pymysql://root:***@127.0.0.1:3307/classicmodels)

In [8]:
with engine.connect() as conn:
    # Показати назви всіх стовпчиків у таблиці клієнтів
    result = conn.execute(text("DESCRIBE customers"))
    for row in result:
        print(row)

('customerNumber', 'int', 'NO', 'PRI', None, '')
('customerName', 'varchar(50)', 'NO', '', None, '')
('contactLastName', 'varchar(50)', 'NO', '', None, '')
('contactFirstName', 'varchar(50)', 'NO', '', None, '')
('phone', 'varchar(50)', 'NO', '', None, '')
('addressLine1', 'varchar(50)', 'NO', '', None, '')
('addressLine2', 'varchar(50)', 'YES', '', None, '')
('city', 'varchar(50)', 'NO', '', None, '')
('state', 'varchar(50)', 'YES', '', None, '')
('postalCode', 'varchar(15)', 'YES', '', None, '')
('country', 'varchar(50)', 'NO', '', None, '')
('salesRepEmployeeNumber', 'int', 'YES', 'MUL', None, '')
('creditLimit', 'decimal(10,2)', 'YES', '', None, '')

In [7]:
def update_customer_phone(customer_id, new_phone):
    with engine.begin() as conn: 
        # команда на оновлення
        conn.execute(
            text("UPDATE customers SET phone = :p WHERE customerNumber = :id"),
            {"p": new_phone, "id": customer_id})
        print(f"Готово! Телефон для клієнта {customer_id} змінено.")


update_customer_phone(103, "+380500000000")

Готово! Телефон для клієнта 103 змінено.

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [6]:
from datetime import datetime

def create_new_order(customer_number, product_code, quantity):
    with engine.begin() as conn:
        # 1. Перевірка наявності товару на складі
        product = conn.execute(
            text("SELECT quantityInStock, buyPrice FROM products WHERE productCode = :code"),
            {"code": product_code}
        ).fetchone()
        
        if not product or product[0] < quantity:
            print(f"❌ Помилка: Товар {product_code} відсутній або недостатньо на складі.")
            return
 # номер замовлення
        last_order = conn.execute(text("SELECT MAX(orderNumber) FROM orders")).scalar()
        new_order_number = last_order + 1

        # 2. Створення запису в таблиці orders
        conn.execute(
            text("""    INSERT INTO orders (orderNumber, orderDate, requiredDate, status, customerNumber)
                VALUES (:num, :date, :req_date, 'In Process', :cust_num) """),
            {
                "num": new_order_number,
                "date": datetime.now().date(),
                "req_date": datetime.now().date(),
                "cust_num": customer_number
            }
                          )

        # 3. Додавання в orderdetails
        conn.execute(
            text("""
                INSERT INTO orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                VALUES (:num, :p_code, :qty, :price, 1)
            """),
            {
                "num": new_order_number,
                "p_code": product_code,
                "qty": quantity,
                "price": product[1]
            }
                          )

        # 4. Зменшення залишків на складі
        conn.execute(
            text("UPDATE products SET quantityInStock = quantityInStock - :qty WHERE productCode = :code"),
            {"qty": quantity, "code": product_code}
        )
        
        print(f"✅ Замовлення №{new_order_number} успішно створено!")

# Запуск із тестовими даними (Клієнт 103, Товар S10_1678, Кількість 5)
create_new_order(103, 'S10_1678', 5)

✅ Замовлення №10427 успішно створено!

In [5]:
print("Перевірка замовлення")
display(pd.read_sql(text("SELECT * FROM orders ORDER BY orderNumber DESC LIMIT 1"), engine))

print("Перевірка деталей замовлення ")
display(pd.read_sql(text("SELECT * FROM orderdetails ORDER BY orderNumber DESC LIMIT 1"), engine))

print(" Перевірка залишків товару ")
display(pd.read_sql(text("SELECT productCode, quantityInStock FROM products WHERE productCode = 'S10_1678'"), engine))

Перевірка замовлення

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10426,2026-03-07,2026-03-07,None,In Process,None,103

Перевірка деталей замовлення

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10426    S10_1678                5      48.81                1

 Перевірка залишків товару

  productCode  quantityInStock
0    S10_1678             7928